apiVersion: 1

contactPoints:
  - orgId: 1
    name: industrial-iot-alerts
    receivers:
      - uid: industrial-iot-email
        type: email
        settings:
          addresses: admin@example.com
          singleEmail: false

policies:
  - orgId: 1
    receiver: industrial-iot-alerts
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: industrial-iot-alerts
        matchers:
          - project = industrial-iot
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
